### ISSUE TITLE
Statement exception for varchar length

### ISSUE THREAD

**Issue by chaoweiyi** [FirebirdSQL/firebird#7544]
```java
try (SqlSession sqlSession = DbPoolFactoryMyBatis.openSession(configName)) {
	Handle h = DBI.open(sqlSession.getConnection());

        // 1
	h.createQuery("SELECT COUNT(1) FROM T_PERSON " +
			"WHERE (F_NAME LIKE '%aVW7tYyyZUUwSppQS1hitSvGvtbkO92LEFSbv0IRa6ze9P5wZ3%' " +
			"AND F_ADDRESS LIKE '%0123456789 0123456789%')")
			.first();
        // 2
	h.createQuery("SELECT COUNT(1) FROM T_PERSON " +
			"WHERE (F_NAME LIKE '%aVW7tYyyZUUwSppQS1hitSvGvtbkO92LEFSbv0IRa6ze9P5wZ3%' " +
			"AND F_ADDRESS = :F_ADDRESS)")
			.bind("F_ADDRESS", "%0123456789%")
			.first();
}
```

第1种方式，执行正常，因为它没有使用statement
第2种方式，执行异常，因为它的长度超出了字符串定义长度，F_ADDRESS varchar(10)，但是加上“%”，长度变成了12
```java
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.SQLException: Dynamic SQL Error; SQL error code = -303; arithmetic exception, numeric overflow, or string truncation; string right truncation; expected length 10, actual 12 [SQLState:22001, ISC error code:335544914] [statement:"SELECT COUNT(1) FROM T_PERSON WHERE (F_NAME LIKE '%aVW7tYyyZUUwSppQS1hitSvGvtbkO92LEFSbv0IRa6ze9P5wZ3%' AND F_ADDRESS = :F_ADDRESS)", located:"SELECT COUNT(1) FROM T_PERSON WHERE (F_NAME LIKE '%aVW7tYyyZUUwSppQS1hitSvGvtbkO92LEFSbv0IRa6ze9P5wZ3%' AND F_ADDRESS = :F_ADDRESS)", rewritten:"SELECT COUNT(1) FROM T_PERSON WHERE (F_NAME LIKE '%aVW7tYyyZUUwSppQS1hitSvGvtbkO92LEFSbv0IRa6ze9P5wZ3%' AND F_ADDRESS = ?)", arguments:{ positional:{}, named:{F_ADDRESS:'%0123456789%'}, finder:[]}]

	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1338)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.first(Query.java:273)
	at org.skife.jdbi.v2.Query.first(Query.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLException: Dynamic SQL Error; SQL error code = -303; arithmetic exception, numeric overflow, or string truncation; string right truncation; expected length 10, actual 12 [SQLState:22001, ISC error code:335544914]
	at org.firebirdsql.gds.ng.FbExceptionBuilder$Type$1.createSQLException(FbExceptionBuilder.java:539)
	at org.firebirdsql.gds.ng.FbExceptionBuilder.toFlatSQLException(FbExceptionBuilder.java:304)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readStatusVector(AbstractWireOperations.java:140)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.processOperation(AbstractWireOperations.java:204)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readSingleResponse(AbstractWireOperations.java:171)
	at org.firebirdsql.gds.ng.wire.AbstractWireOperations.readResponse(AbstractWireOperations.java:155)
	at org.firebirdsql.gds.ng.wire.AbstractFbWireDatabase.readResponse(AbstractFbWireDatabase.java:211)
	at org.firebirdsql.gds.ng.wire.version10.V10Statement.execute(V10Statement.java:329)
	at org.firebirdsql.jdbc.AbstractPreparedStatement.internalExecute(AbstractPreparedStatement.java:538)
	at org.firebirdsql.jdbc.AbstractPreparedStatement.execute(AbstractPreparedStatement.java:487)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3446)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:434)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3444)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:152)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:483)
	at com.p6spy.engine.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:362)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1327)
	... 29 more
Caused by: org.firebirdsql.jdbc.FBSQLExceptionInfo: Dynamic SQL Error
```

我查了很多资料，从2.x版本开始，就有这个问题，无论是数据库，还是驱动，都没有解决它。
这个问题其实对使用影响很大，对编码的方式影响也非常大，我不能把所有的参数，都处理一遍。

为什么不能从数据库，或者驱动解决这个问题，比方加入设置或者设置参数，这样我设置了，我就会承担带来的风险，但是我的编码方式，以及用户的操作不需要修改。

English translation

The first method executes normally because it does not use a statement

The second method is to execute an exception because its length exceeds the defined length of the string_ ADDRESS varchar (10), but with '%' added, the length becomes 12

I have checked a lot of information, and since version 2. x, there has been this issue, whether it is the database or the driver, it has not been resolved.

This issue actually has a significant impact on usage and the encoding method. I cannot handle all the parameters once.

Why can't I solve this problem from the database or driver, such as adding settings or setting parameters, so that if I set them, I will bear the risk, but my coding method and user actions do not need to be modified.

**Comment by chaoweiyi** [comment]
```sql
CREATE TABLE T_PERSON (
	F_ID VARCHAR(32),
	F_NAME BLOB SUB_TYPE TEXT,
	F_ADDRESS VARCHAR(10)
);
```

**Comment by chaoweiyi** [comment]
@asfernandes

**Comment by chaoweiyi** [comment]
@asfernandes Sorry to bother you, could you please take a look at this question?

**Comment by mrotteveel** [comment]
Duplicates https://github.com/FirebirdSQL/firebird/issues/1361
